substitutions:
  clkpin: GPIO13
  mosi: GPIO44
  miso: GPIO43
  cs_pin: GPIO01
  gdo0_pin: GPIO12
  gdo1_pin: GPIO11
  led_pin: GPIO48

esphome:
  name: honklockgateway2
  friendly_name: HonklockGateway2
  min_version: 2026.4.0
  name_add_mac_suffix: false

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

# Modular packages: Include either or both depending on the devices in your system
packages:
  ivac: !include gateway_ivac.yaml
  arlec_rc210: !include gateway_arlec_rc210.yaml

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

# SPI configuration for the CC1101 transceiver
spi:
  clk_pin: ${clkpin}
  mosi_pin: ${mosi}
  miso_pin: ${miso}

# Configure the CC1101 transceiver hardware registers
cc1101:
  id: my_cc1101
  cs_pin: ${cs_pin}
  filter_bandwidth: 325kHz
  frequency: 433.92MHz
  manchester: true

# Configures the RF Transmitter output pin (using CC1101 GDO0)
remote_transmitter:
  id: rf_tx
  pin: ${gdo0_pin}
  carrier_duty_percent: 100%
  non_blocking: true
  rmt_symbols: 48
  on_transmit:
    - lambda: |-
        ESP_LOGI("rf_tx", "CC1101 entering TX mode and transmitting pulses...");
    - cc1101.begin_tx: my_cc1101
  on_complete:
    - lambda: |-
        ESP_LOGI("rf_tx", "Transmission finished, CC1101 returning to IDLE mode.");
    - cc1101.set_idle: my_cc1101

# Configures the RF Receiver listening pin (using CC1101 GDO2) for on-demand learning
remote_receiver:
  id: rf_rx
  pin: ${gdo1_pin}
  dump: []
  filter: 50us
  idle: 20ms
  buffer_size: 2kb
  rmt_symbols: 48

# ESP32-S3-SuperMini Onboard WS2812B RGB LED (GPIO48)
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: ${led_pin}
    num_leds: 1
    chipset: ws2812
    rmt_symbols: 48
    name: "Onboard LED"
    id: onboard_led
    internal: true
    effects:
      - strobe:
          name: "Blink"
          colors:
            - state: true
              brightness: 100%
              red: 0%
              green: 0%
              blue: 100%
              duration: 250ms
            - state: false
              duration: 250ms