author: Paul Jenkins
name: HonkLock
version: 0.1
source: https://github.com/TemuWolverine/HonkLock
labels: [servo, woodworking, esp32]
---

substitutions:
  friendly_name: HonkLock Tablesaw
  device_name: honklock_tablesaw
  servo_pin: GPIO07

packages:
  esphome_templates:
    url: https://github.com/TemuWolverine/esphome_templates
    ref: main
    refresh: 1d
    files:
      - esphome_boilerplate.yaml
      - boards/waveshare_esp32_s3_zero.yaml

servo:
  - id: my_servo
    output: pwm_output
    
output:
  - platform: ledc 
    id: pwm_output
    pin: ${servo_pin}
    frequency: 50Hz
    
globals:
  - id: gatestate
    type: bool
    restore_value: yes
    initial_value: 'false'
    
switch:
  - platform: template
    id: gate
    name: "Gate"
    optimistic: true
    assumed_state: true

    turn_on_action: 
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return 0.0;'
    turn_off_action: 
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return -100.0;'
    
    